[package]
name = "ya_iam"
version = "1.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
